Codebook
========================================================

Original Dataset
----------------
The original source of the data for this project is taken from the Human Activity Recognition Using Smartphones Dataset Version 1.0 as compiled by:

> Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
> Smartlab - Non Linear Complex Systems Laboratory
> DITEN - Universit‡ degli Studi di Genova.
> Via Opera Pia 11A, I-16145, Genoa, Italy.
> activityrecognition@smartlab.ws
> www.smartlab.ws

> Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012


Naming Strategy
---------------

The variable names in the original dataset have been altered to make them more readable and compiant with the R programming language standards.  The varialbes have had all symbols ("-", "(", and ")") removed, and the words expanded to be more udnerstandable. Additionally, due to the length of the variables, "camelCase" is used to make them more readable.

For instance, *tBodyAcc-mean()-Y* has been transformed into *tBodyAccelerometerMeanYAxis*.

However, both the "t" and the "f" prefixes have been retained. A "t" prefix indicates that the variable is in the time domain, while an "f" indicates frequency domain, as obtainted through a Fast Fourier Transformation (FFT).

Detailed Description of Variables
---------------------------------

|    | Variable Name                                        | Variable Description                                                                                                                                                                                                                                                  |
|----|------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1  | Person                                               | The subject of the experimental measurements.                                                                                                                                                                                                                         |
| 2  | ActivityDescription                                  | The activity measured as part of the data collection.                                                                                                                                                                                                                 |
| 3  | tBodyAccelerometerMeanXAxis                          | The mean value of the time domain signal as measured on the Accelerometer's X axis and corresponding to the body portion of the signal.                                                                                                                               |
| 4  | tBodyAccelerometerMeanYAxis                          | The mean value of the time domain signal as measured on the Accelerometer's Y axis and corresponding to the body portion of the signal.                                                                                                                               |
| 5  | tBodyAccelerometerMeanZAxis                          | The mean value of the time domain signal as measured on the Accelerometer's Z axis and corresponding to the body portion of the signal.                                                                                                                               |
| 6  | tGravityAccelerometerMeanXAxis                       | The mean value of the time domain signal as measured on the Accelerometer's X axis and corresponding to the gravity portion of the signal.                                                                                                                            |
| 7  | tGravityAccelerometerMeanYAxis                       | The mean value of the time domain signal as measured on the Accelerometer's Y axis and corresponding to the gravity portion of the signal.                                                                                                                            |
| 8  | tGravityAccelerometerMeanZAxis                       | The mean value of the time domain signal as measured on the Accelerometer's Z axis and corresponding to the gravity portion of the signal.                                                                                                                            |
| 9  | tBodyAccelerometerJerkMeanXAxis                      | The mean value of the time domain signal as measured on the Accelerometer's X axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                          |
| 10 | tBodyAccelerometerJerkMeanYAxis                      | The mean value of the time domain signal as measured on the Accelerometer's Y axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                          |
| 11 | tBodyAccelerometerJerkMeanZAxis                      | The mean value of the time domain signal as measured on the Accelerometer's Z axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                          |
| 12 | tBodyGyroscopeMeanXAxis                              | The mean value of the time domain signal as measured on the Gyroscope's X axis and corresponding to the body portion of the signal.                                                                                                                                   |
| 13 | tBodyGyroscopeMeanYAxis                              | The mean value of the time domain signal as measured on the Gyroscope's Y axis and corresponding to the body portion of the signal.                                                                                                                                   |
| 14 | tBodyGyroscopeMeanZAxis                              | The mean value of the time domain signal as measured on the Gyroscope's Z axis and corresponding to the body portion of the signal.                                                                                                                                   |
| 15 | tBodyGyroscopeJerkMeanXAxis                          | The mean value of the time domain signal as measured on the Gyroscope's X axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                              |
| 16 | tBodyGyroscopeJerkMeanYAxis                          | The mean value of the time domain signal as measured on the Gyroscope's Y axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                              |
| 17 | tBodyGyroscopeJerkMeanZAxis                          | The mean value of the time domain signal as measured on the Gyroscope's Z axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                              |
| 18 | tBodyAccelerometerMagnitudeMean                      | The mean value of the time domain signal as measured on the Accelerometer for the magnitude of the body portion of the signal.                                                                                                                                        |
| 19 | tGravityAccelerometerMagnitudeMean                   | The mean value of the time domain signal as measured on the Accelerometer for the magnitude of the gravity portion of the signal.                                                                                                                                     |
| 20 | tBodyAccelerometerJerkMagnitudeMean                  | The mean value of the time domain signal as measured on the Accelerometer corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal.                                                                             |
| 21 | tBodyGyroscopeMagnitudeMean                          | The mean value of the time domain signal as measured on the Gyroscope for the magnitude of the body portion of the signal.                                                                                                                                            |
| 22 | tBodyGyroscopeJerkMagnitudeMean                      | The mean value of the time domain signal as measured on the Gyroscope corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal.                                                                                 |
| 23 | fBodyAccelerometerMeanXAxis                          | The mean value of the frequency domain signal as measured on the Accelerometer's X axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                    |
| 24 | fBodyAccelerometerMeanYAxis                          | The mean value of the frequency domain signal as measured on the Accelerometer's Y axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                    |
| 25 | fBodyAccelerometerMeanZAxis                          | The mean value of the frequency domain signal as measured on the Accelerometer's Z axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                    |
| 26 | fBodyAccelerometerJerkMeanXAxis                      | The mean value of the frequency domain signal as measured on the Accelerometer's X axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function).               |
| 27 | fBodyAccelerometerJerkMeanYAxis                      | The mean value of the frequency domain signal as measured on the Accelerometer's Y axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function).               |
| 28 | fBodyAccelerometerJerkMeanZAxis                      | The mean value of the frequency domain signal as measured on the Accelerometer's Z axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function).               |
| 29 | fBodyGyroscopeMeanXAxis                              | The mean value of the frequency domain signal as measured on the Gyroscope's X axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                        |
| 30 | fBodyGyroscopeMeanYAxis                              | The mean value of the frequency domain signal as measured on the Gyroscope's Y axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                        |
| 31 | fBodyGyroscopeMeanZAxis                              | The mean value of the frequency domain signal as measured on the Gyroscope's Z axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                        |
| 32 | fBodyAccelerometerMagnitudeMean                      | The mean value of the frequency domain signal as measured on the Accelerometer for the magnitude of the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                             |
| 33 | fBodyBodyAccelerometerJerkMagnitudeMean              | The mean value of the frequency domain signal as measured on the Accelerometer corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function).                  |
| 34 | fBodyBodyGyroscopeMagnitudeMean                      | The mean value of the frequency domain signal as measured on the Gyroscope for the magnitude of the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                                 |
| 35 | fBodyBodyGyroscopeJerkMagnitudeMean                  | The mean value of the frequency domain signal as measured on the Gyroscope corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal  (as compiled using a Fast Fourier Transform function).                     |
| 36 | tBodyAccelerometerStandardDeviationXAxis             | The standard deviation value of the time domain signal as measured on the Accelerometer's X axis and corresponding to the body portion of the signal.                                                                                                                 |
| 37 | tBodyAccelerometerStandardDeviationYAxis             | The standard deviation value of the time domain signal as measured on the Accelerometer's Y axis and corresponding to the body portion of the signal.                                                                                                                 |
| 38 | tBodyAccelerometerStandardDeviationZAxis             | The standard deviation value of the time domain signal as measured on the Accelerometer's Z axis and corresponding to the body portion of the signal.                                                                                                                 |
| 39 | tGravityAccelerometerStandardDeviationXAxis          | The standard deviation value of the time domain signal as measured on the Accelerometer's X axis and corresponding to the gravity portion of the signal.                                                                                                              |
| 40 | tGravityAccelerometerStandardDeviationYAxis          | The standard deviation value of the time domain signal as measured on the Accelerometer's Y axis and corresponding to the gravity portion of the signal.                                                                                                              |
| 41 | tGravityAccelerometerStandardDeviationZAxis          | The standard deviation value of the time domain signal as measured on the Accelerometer's Z axis and corresponding to the gravity portion of the signal.                                                                                                              |
| 42 | tBodyAccelerometerJerkStandardDeviationXAxis         | The standard deviation value of the time domain signal as measured on the Accelerometer's X axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                            |
| 43 | tBodyAccelerometerJerkStandardDeviationYAxis         | The standard deviation value of the time domain signal as measured on the Accelerometer's Y axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                            |
| 44 | tBodyAccelerometerJerkStandardDeviationZAxis         | The standard deviation value of the time domain signal as measured on the Accelerometer's Z axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                            |
| 45 | tBodyGyroscopeStandardDeviationXAxis                 | The standard deviation value of the time domain signal as measured on the Gyroscope's X axis and corresponding to the body portion of the signal.                                                                                                                     |
| 46 | tBodyGyroscopeStandardDeviationYAxis                 | The standard deviation value of the time domain signal as measured on the Gyroscope's Y axis and corresponding to the body portion of the signal.                                                                                                                     |
| 47 | tBodyGyroscopeStandardDeviationZAxis                 | The standard deviation value of the time domain signal as measured on the Gyroscope's Z axis and corresponding to the body portion of the signal.                                                                                                                     |
| 48 | tBodyGyroscopeJerkStandardDeviationXAxis             | The standard deviation value of the time domain signal as measured on the Gyroscope's X axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                |
| 49 | tBodyGyroscopeJerkStandardDeviationYAxis             | The standard deviation value of the time domain signal as measured on the Gyroscope's Y axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                |
| 50 | tBodyGyroscopeJerkStandardDeviationZAxis             | The standard deviation value of the time domain signal as measured on the Gyroscope's Z axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal.                                                                |
| 51 | tBodyAccelerometerMagnitudeStandardDeviation         | The standard deviation value of the time domain signal as measured on the Accelerometer for the magnitude of the body portion of the signal.                                                                                                                          |
| 52 | tGravityAccelerometerMagnitudeStandardDeviation      | The standard deviation value of the time domain signal as measured on the Accelerometer for the magnitude of the gravity portion of the signal.                                                                                                                       |
| 53 | tBodyAccelerometerJerkMagnitudeStandardDeviation     | The standard deviation value of the time domain signal as measured on the Accelerometer corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal.                                                               |
| 54 | tBodyGyroscopeMagnitudeStandardDeviation             | The standard deviation value of the time domain signal as measured on the Gyroscope for the magnitude of the body portion of the signal.                                                                                                                              |
| 55 | tBodyGyroscopeJerkMagnitudeStandardDeviation         | The standard deviation value of the time domain signal as measured on the Gyroscope corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal.                                                                   |
| 56 | fBodyAccelerometerStandardDeviationXAxis             | The standard deviation value of the frequency domain signal as measured on the Accelerometer's X axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                      |
| 57 | fBodyAccelerometerStandardDeviationYAxis             | The standard deviation value of the frequency domain signal as measured on the Accelerometer's Y axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                      |
| 58 | fBodyAccelerometerStandardDeviationZAxis             | The standard deviation value of the frequency domain signal as measured on the Accelerometer's Z axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                      |
| 59 | fBodyAccelerometerJerkStandardDeviationXAxis         | The standard deviation value of the frequency domain signal as measured on the Accelerometer's X axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function). |
| 60 | fBodyAccelerometerJerkStandardDeviationYAxis         | The standard deviation value of the frequency domain signal as measured on the Accelerometer's Y axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function). |
| 61 | fBodyAccelerometerJerkStandardDeviationZAxis         | The standard deviation value of the frequency domain signal as measured on the Accelerometer's Z axis and corresponding to the body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function). |
| 62 | fBodyGyroscopeStandardDeviationXAxis                 | The standard deviation value of the frequency domain signal as measured on the Gyroscope's X axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                          |
| 63 | fBodyGyroscopeStandardDeviationYAxis                 | The standard deviation value of the frequency domain signal as measured on the Gyroscope's Y axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                          |
| 64 | fBodyGyroscopeStandardDeviationZAxis                 | The standard deviation value of the frequency domain signal as measured on the Gyroscope's Z axis and corresponding to the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                          |
| 65 | fBodyAccelerometerMagnitudeStandardDeviation         | The standard deviation value of the frequency domain signal as measured on the Accelerometer for the magnitude of the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                               |
| 66 | fBodyBodyAccelerometerJerkMagnitudeStandardDeviation | The standard deviation value of the frequency domain signal as measured on the Accelerometer corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function).    |
| 67 | fBodyBodyGyroscopeMagnitudeStandardDeviation         | The standard deviation value of the frequency domain signal as measured on the Gyroscope for the magnitude of the body portion of the signal (as compiled using a Fast Fourier Transform function).                                                                   |
| 68 | fBodyBodyGyroscopeJerkMagnitudeStandardDeviation     | The standard deviation value of the frequency domain signal as measured on the Gyroscope corresponding to the magnitude body linear acceleration and angular velocity of the body portion of the signal (as compiled using a Fast Fourier Transform function).        |

Activity Labels
---------------
The subjects of the experiment participated in the activity listed below during the experiment:

1. Walking
2. Walking Upstairs
3. Walking Downstairs
4. Sitting
5. Standing
6. Laying Down
